"""EventFilter: prevents feedback loops and deduplicates webhook events.

Checks whether an event was generated by the bot itself (via bot_user_id)
and applies time-based debouncing to avoid processing the same task+event
multiple times within a short window.
"""
import logging
import time

logger = logging.getLogger(__name__)

# Default debounce window in seconds
DEFAULT_DEBOUNCE_SECONDS = 30

# Prune entries older than this (seconds)
PRUNE_THRESHOLD_SECONDS = 300


class EventFilter:
    """Filters out bot-generated and duplicate ClickUp webhook events."""

    def __init__(self, bot_user_id: str, debounce_seconds: int = DEFAULT_DEBOUNCE_SECONDS):
        self._bot_user_id = bot_user_id
        self._debounce_seconds = debounce_seconds
        # Key: "{task_id}:{event_type}" -> timestamp of last processed event
        self._recent: dict[str, float] = {}

    def is_bot_event(self, event: dict) -> bool:
        """Check if the event was triggered by the bot's own actions.

        Inspects history_items[].user.id for a match with bot_user_id.
        For taskCreated events, checks the top-level user field.
        """
        if not self._bot_user_id:
            return False

        # taskCreated has a top-level "user" field instead of history_items
        event_user = event.get("user", {})
        if str(event_user.get("id", "")) == self._bot_user_id:
            return True

        for item in event.get("history_items", []):
            user = item.get("user", {})
            if str(user.get("id", "")) == self._bot_user_id:
                return True

        return False

    def is_debounced(self, task_id: str, event_type: str) -> bool:
        """Check if this task+event combination was processed recently.

        Returns True if the same task_id+event_type was seen within the
        debounce window, meaning it should be skipped.
        """
        if not task_id:
            return False

        key = f"{task_id}:{event_type}"
        now = time.monotonic()

        last_seen = self._recent.get(key)
        if last_seen is not None and (now - last_seen) < self._debounce_seconds:
            return True

        self._recent[key] = now
        self._prune(now)
        return False

    def _prune(self, now: float) -> None:
        """Remove entries older than PRUNE_THRESHOLD_SECONDS."""
        expired = [
            key for key, ts in self._recent.items()
            if (now - ts) > PRUNE_THRESHOLD_SECONDS
        ]
        for key in expired:
            del self._recent[key]
